#!/usr/bin/env python3
"""Bundle a curated set of Twemoji SVGs into emoji.js so icons render on every device, offline.

Usage:
  npm pack @iconify-json/twemoji@1.2.5 && tar xzf iconify-json-twemoji-1.2.5.tgz
  python3 tools/build_emoji.py package > emoji.js

Twemoji graphics: Copyright Twitter, Inc and other contributors, licensed CC-BY 4.0
(https://creativecommons.org/licenses/by/4.0/). Source: https://github.com/jdecked/twemoji
"""
import json
import os
import sys

# Shown in this order in the Settings icon picker.
EMOJI = [
    # Prizes & awards
    "🏆", "🥇", "🥈", "🥉", "🏅", "🎖️", "👑", "💎", "💍", "💰", "💵", "💳",
    "🎁", "🎀", "🎟️", "🎫", "🛍️", "👜", "🎒", "👕", "🧢", "🕶️", "⌚", "📱",
    "💻", "🎧", "🎮", "📷", "🔋", "🖊️", "✏️", "📓", "📚", "🧸", "🎲", "🧩",
    "🎈", "🎉", "🎊", "✨", "⭐", "🌟", "💫", "🔥",
    # Treats
    "🍬", "🍭", "🍫", "🍩", "🍪", "🧁", "🍰", "🍦", "🍿", "🥤", "☕", "🍕",
    "🍔", "🌮", "🍎", "🍓", "🍉", "🥗",
    # Health & wellness
    "🩺", "💊", "🩹", "🧴", "🧼", "🦷", "💪", "🧘", "🏃", "💧", "🧪", "🔬", "❤️",
    # Fun
    "🌸", "🌻", "🪴", "🐶", "🐱", "🦄", "🚗", "✈️", "🏖️", "🎬", "🎵", "🎤",
    "⚽", "🏀", "🎯", "🎳",
    # No prize
    "🔄", "🔁", "😅", "🍀", "😢", "🙈", "😬", "🤞", "👋", "🙏", "💔", "🌈",
    "⏳", "😊", "👍", "🫶",
    # UI
    "👥",
]


def key(ch):
    return "-".join(f"{ord(c):x}" for c in ch if ord(c) != 0xFE0F)


def main(pkg):
    chars = json.load(open(os.path.join(pkg, "chars.json")))
    data = json.load(open(os.path.join(pkg, "icons.json")))
    icons, aliases = data["icons"], data.get("aliases", {})
    w, h = data.get("width", 36), data.get("height", 36)
    out, missing = {}, []
    for ch in EMOJI:
        name = chars.get(key(ch))
        while name in aliases:
            name = aliases[name]["parent"]
        if not name or name not in icons:
            missing.append(ch)
            continue
        out[ch.replace("️", "")] = (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}">{icons[name]["body"]}</svg>'
        )
    if missing:
        sys.exit(f"Not found in Twemoji: {' '.join(missing)}")
    order = [ch.replace("️", "") for ch in EMOJI if ch != "👥"]
    sys.stdout.write(
        "// Generated by tools/build_emoji.py. Do not edit by hand.\n"
        "// Twemoji graphics (c) Twitter, Inc and other contributors, CC-BY 4.0: https://github.com/jdecked/twemoji\n"
        f"window.PRIZE_EMOJI = {{ list: {json.dumps(order, ensure_ascii=False)},\n"
        f"  svg: {json.dumps(out, ensure_ascii=False, indent=0)} }};\n"
    )


if __name__ == "__main__":
    main(sys.argv[1])
